//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace İnternetCafeSistemi
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableOturumlar
    {
        public int OturumID { get; set; }
        public Nullable<int> KullaniciID { get; set; }
        public Nullable<int> MasaID { get; set; }
        public Nullable<System.DateTime> BaslangicZamani { get; set; }
        public Nullable<System.DateTime> BitisZamanı { get; set; }
        public Nullable<int> KullanilanSure { get; set; }
        public Nullable<decimal> Ucret { get; set; }
    
        public virtual TableKullanicilar TableKullanicilar { get; set; }
        public virtual TableMasalar TableMasalar { get; set; }
    }
}
