//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace İnternetCafeSistemi
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableHareketler
    {
        public int HareketID { get; set; }
        public Nullable<int> KullaniciID { get; set; }
        public Nullable<int> MasaID { get; set; }
        public string IslemTuru { get; set; }
        public System.DateTime IslemZamani { get; set; }
    
        public virtual TableKullanicilar TableKullanicilar { get; set; }
        public virtual TableKullanicilar TableKullanicilar1 { get; set; }
        public virtual TableMasalar TableMasalar { get; set; }
        public virtual TableMasalar TableMasalar1 { get; set; }
    }
}
